project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - co-work-oct-25.qmd
    - REST-API-feb-28.qmd

website:
  title: "Misc Presentations"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - co-work-oct-25.qmd
      - text: "REST API Feb 2023"
        file: REST-API-feb-28.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true