project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - co-work-oct-25.qmd
    - REST-API-feb-28.qmd
    - Agile-Mar-3-2023.qmd

website:
  title: "Misc Presentations"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - co-work-oct-25.qmd
      - text: "REST API Feb 2023"
        file: REST-API-feb-28.qmd
      - text: "Fish 549 Mar 2023"
        file: Agile-Mar-3-2023.qmd


format:
  html:
    theme: cosmo
    toc: true
    self-contained: true